version: '3.2'

services:

  db:
    image: mariadb:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordrpess
      MYSQL_PASSWORD: wordpress
    command: mysqld --debug-no-sync
    ports:
      - "4406:3306"

  wp:
    build:
      context: .
      dockerfile: docker/wordpress/Dockerfile
    image: ${COMPOSE_PROJECT_NAME:-wpbrowser}_wp:latest
    links:
      - db
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ""

  chromedriver:
    image: selenium/standalone-chrome:3.141.59-oxygen
    links:
      - "wp:wp.test"
      - "wp:test1.wp.test"
      - "wp:test2.wp.test"

  db_waiter:
    image: waisbrot/wait
    links:
      - db
    environment:
      - TARGETS=db:3306

  wp_waiter:
    image: waisbrot/wait
    links:
      - db
      - wp
    environment:
      - TARGETS=db:3306,wp:80

  web_waiter:
    image: waisbrot/wait
    links:
      - db
      - wp
      - chromedriver
    environment:
      - TARGETS=db:3306,wp:80,chromedriver:4444

  test_runner:
    # Instead of using a pre-built image, let's build it from the file.
    build:
      context: .
      dockerfile: docker/test_runner/Dockerfile
      args:
        # By default use PHP 7.3 but allow overriding the version.
        BUILD_PHP_VERSION: ${BUILD_PHP_VERSION:-7.3}
        BUILD_PHP_TIMEZONE: ${BUILD_PHP_TIMEZONE:-UTC}
        BUILD_PHP_IDEKEY: ${BUILD_PHP_IDEKEY:-PHPSTORM}
        BUILD_XDEBUG_ENABLE: ${BUILD_XDEBUG_ENABLE:-1}
    image: wpbrowser_test_runner:latest
    volumes:
      - ./tests:/project/tests
    environment:
      # As XDebug remote host use the host hostname on Docker for Mac or Windows, but allow overriding it.
      # Build systems are usually Linux-based.
      # Use default port, 9000, by default.
      XDEBUG_CONFIG: "remote_host=${XDEBUG_REMOTE_HOST:-host.docker.internal} remote_port=${XDEBUG_REMOTE_PORT:-9000}"
      # I use PHPStorm as IDE and this makes the handshake easier.
      PHP_IDE_CONFIG: "serverName=wp.test"

  wp_test_runner:
    image: wpbrowser_test_runner:latest
    volumes:
      - ./tests:/project/tests
    links:
      - db
      - wp
    environment:
      # As XDebug remote host use the host hostname on Docker for Mac or Windows, but allow overriding it.
      # Build systems are usually Linux-based.
      # Use default port, 9000, by default.
      XDEBUG_CONFIG: "remote_host=${XDEBUG_REMOTE_HOST:-host.docker.internal} remote_port=${XDEBUG_REMOTE_PORT:-9000}"
      # I use PHPStorm as IDE and this makes the handshake easier.
      PHP_IDE_CONFIG: "serverName=wp.test"

  web_test_runner:
    image: wpbrowser_test_runner:latest
    volumes:
      - ./tests:/project/tests
    links:
      - db
      - wp
      - chromedriver
    environment:
      # As XDebug remote host use the host hostname on Docker for Mac or Windows, but allow overriding it.
      # Build systems are usually Linux-based.
      # Use default port, 9000, by default.
      XDEBUG_CONFIG: "remote_host=${XDEBUG_REMOTE_HOST:-host.docker.internal} remote_port=${XDEBUG_REMOTE_PORT:-9000}"
      # I use PHPStorm as IDE and this makes the handshake easier.
      PHP_IDE_CONFIG: "serverName=wp.test"
